// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1Pekg3eraXzaN_yj8WfBWOPBY1gadYQ',
    appId: '1:931756988579:web:93920b5d9de7d9a03c0716',
    messagingSenderId: '931756988579',
    projectId: 'fathah-dc98c',
    authDomain: 'fathah-dc98c.firebaseapp.com',
    storageBucket: 'fathah-dc98c.appspot.com',
    measurementId: 'G-CVTFYH9M2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGpWAvRcn7oSxWUtmckW3OAZCqmX0rwaM',
    appId: '1:931756988579:android:c1888b939c80cd6e3c0716',
    messagingSenderId: '931756988579',
    projectId: 'fathah-dc98c',
    storageBucket: 'fathah-dc98c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTuML9vqIDzGcQAOuUB-BggwJtiVwutw',
    appId: '1:931756988579:ios:35f3fd12010425423c0716',
    messagingSenderId: '931756988579',
    projectId: 'fathah-dc98c',
    storageBucket: 'fathah-dc98c.appspot.com',
    iosClientId: '931756988579-el332j7m5nujrsjear1lkhai0hq06ge7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fathah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTuML9vqIDzGcQAOuUB-BggwJtiVwutw',
    appId: '1:931756988579:ios:35f3fd12010425423c0716',
    messagingSenderId: '931756988579',
    projectId: 'fathah-dc98c',
    storageBucket: 'fathah-dc98c.appspot.com',
    iosClientId: '931756988579-el332j7m5nujrsjear1lkhai0hq06ge7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fathah',
  );
}
